### ISSUE TITLE
Set up branch defaulting to main

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#11]
Currently we set the default branch in the controller, let's have a webhook do that instead. We can add further things to this as we like.

**Comment by aclevername** [comment]
@Callisto13 do we want a separate ticket for setting up a validation webhook?

**Comment by Callisto13** [comment]
Oh lol i totally did not specify which kind

And yes, makes sense to have in a separate PR

**Comment by bigkevmcd** [comment]
Probably want to look at ` operator-sdk create webhook`
