### ISSUE TITLE
Profile installation via Git

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#114]
**What feature/behavior/change do you want?**
Installing a profile.

This is about installing a profile to a "git repository".

Assuming that you have a cluster configuration repository, installation of a
profile should look like this:

This also assumes that the profile has helm-chart references.

```shell
$ pctl install https://github.com/weaveworks/nginx-profile.git
```

This should result in the generation of several files relative to the cluster
configuration repository root.

In the paths below, the `nginx-profile` part should come from the profile-name
(let's not worry too much about conflicts here).

```
/profiles/nginx-profile/profile.yaml
/profiles/nginx-profile/artifacts/helm-release.yaml
/profiles/nginx-profile/artifacts/helm-repository.yaml
```

To get there, I suspect that we need to rename the `ProfileDefinition` to a
`Profile`, there's no controller (initially) for this, but the CR is installed
into the cluster.

To deploy this, we'd be deploying the `artifacts` directory.

For this iteration, we need to side-step values configuration.

**Why do you want this feature?**

**Comment by aclevername** [comment]
Few questions @bigkevmcd :

1. With this change, do we want to update `pctl get/list` to instead search your git repository for `profile.yaml`'s? If so shall we create some new sub-issues?
2. Is the `profile.yaml` just for metadata around what this profile installation is ? (e.g. catalog/profile/version)? 
3. `side-step values configuration.` just to be clear, does this mean not to worry about the values workflow that exists for the profile subsription workflow?

**Comment by bigkevmcd** [comment]
Good questions...

1. Not quite, they should continue to hit the catalog
2. Yes, it's applied _into_ the cluster tho as a CR, there's just no reconciliation, but it's how we find out the "installed" profiles in a cluster.
3. yes, there's some decisions that still need to be taken

**Comment by aclevername** [comment]
> 1. Not quite, they should continue to hit the catalog

`get/list` are for "installed" profiles, not for fetching from the catalog, thats `search` and `show` :smile: . But based upon your answer
 for 2., I'm assuming the answer is actually to search k8s for the profiles CR, like we do for the profile subscriptions


> 2. Yes, it's applied _into_ the cluster tho as a CR, there's just no reconciliation, but it's how we find out the "installed" profiles in a cluster.

:ok_hand: 

> 3. yes, there's some decisions that still need to be taken

 :ok_hand:

**Comment by aclevername** [comment]
> 2. Yes, it's applied _into_ the cluster tho as a CR, there's just no reconciliation, but it's how we find out the "installed" profiles in a cluster.

Re-reading this @bigkevmcd , it sounds exactly the same the the `ProfileSubscription`? But just used for providing information only

**Comment by bigkevmcd** [comment]
It's not quite, it's a `ProfileDefinition` from our current setup.

**Comment by aclevername** [comment]
> It's not quite, it's a `ProfileDefinition` from our current setup.

I don't follow @bigkevmcd . Could you provide an example of what this would contain? We don't currently have the ` catalog/profile/version` inside a `ProfileDefinition`

**Comment by aclevername** [comment]
I've left it as the `ProfileSubscription` for the intial PR, this has the added benefit of preserving the `pctl get/list` code. Once we know what we want in the `profile.yaml` we can update this and the `get/list` logic
