### ISSUE TITLE
[Spike] Explores ways of extracting profiles from private Git repository

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#127]
**What feature/behavior/change do you want?**
Currently we have a simple hard-coded set of profiles in a catalog source.

```go
// ProfileCatalogSourceSpec defines the desired state of ProfileCatalogSource
type ProfileCatalogSourceSpec struct {
	// Profiles is the list of profiles exposed by the catalog
	Profiles []ProfileDescription `json:"profiles,omitempty"`
}
```

# Possible solutions

## GitRepository resource

This is a proposal to alternatively, parse a Flux `GitRepository` artifact for profiles, something like:

```go
type GitRepositoryReference corev1.LocalObjectReference

// ProfileCatalogSourceSpec defines the desired state of ProfileCatalogSource
type ProfileCatalogSourceSpec struct {
	// Profiles is the list of profiles exposed by the catalog
	Profiles []ProfileDescription `json:"profiles,omitempty"`
        GitRepository *GitRepositoryReference `json:"gitRepository,omitempty"`
}
````

This would point at a Flux GitRepository in the same namespace (for simplicity of access).

We should grab the status from this object, which includes the SHA and the URL for downloading the source as a tarball.

We should look for `profile.yaml` files in the tarball, parse and index the data just as if it was an embedded profile.

**Why do you want this feature?**

This is necessary to access profiles stored in Git repositories.

I suspect we'll need more, to do versioning of the repo etc.

## Outcomes
A set of proposals on how to solve this, with some (hacky) demos

**Comment by Callisto13** [comment]
Spike branch https://github.com/weaveworks/profiles/blob/spike-detect-profiles/pkg/detector/detector.go

In which we:
- when given a url to a repo containing profiles
- use `git ls-remote --tags` to get tags on the repo
- parse those tags
- create GitRepository objects pointing to each tag (only tarring the profile.yaml)
- untar each repo archive
- parse each profile.yaml
- populate catalog

This can all be refactored and used from the Catalog controller. Further functionality would include:
- Passing in the secret for auth against private repo
- Checking whether a profile tag was already in the catalog by matching against catalog entries OR gitrepo objects, and then only creating/adding if not found

**Comment by aclevername** [comment]
when we run `git ls-remote ` we will have to add the ssh-key/credentials for communicating the private repo. Lets look at how the source-controller parses and uses the ssh key and copy them
