### ISSUE TITLE
Introduce proper logging and error handling in profiles

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/profiles#143]
Right now the api calls always, no matter the circumstance, return 404. And there is no logging in any of the calls so it's rather difficult to understand what actually failed. And even if there are no results, which is sometimes valid, it returns a 404 which is dealt with an error. So we don't know in pctl if it failed because it didn't find anything or failed because there was an error.

**Comment by aclevername** [comment]
@Skarlso also we should move away from `fmt.Println` into some sort of wrapper, so we don't spam our output in tests & can easy change the format (e.g. timestamp prefxies). Eksctl does something similar with https://github.com/kris-nova/logger

**Comment by bigkevmcd** [comment]
[`go-logr`](https://github.com/go-logr/logr) has a number of implementations that work nicely.

**Comment by Skarlso** [comment]
I like [Zerolog](https://github.com/rs/zerolog) because it's pretty slick and has the ability to add context to logging. So you set it up with a context like a request ID or a name, or whatever, and from there on, every `log.Whatever` will contain that context. But let's use something eksctl is already using so we don't use things all over the place? :)

**Comment by aclevername** [comment]
@bigkevmcd @Skarlso I'm changing this scope to be just for `profiles`. How we do logging and printing in pctl should discussed and adjusted by output of https://github.com/weaveworks/pctl/issues/77. We want a standard approach across our CLI's
