### ISSUE TITLE
Switch to gRPC gateway API

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#165]
**What feature/behavior/change do you want?**
Currently, we have a hand-rolled path-based API, we are standardising on gRPC via grpc-gateway.

We should define an API proto and move our API code to use it.

**Why do you want this feature?**

API standardisation!

Essentially we want to have standards around the APIs exposed by our components to make it easier to build clients.

**Comment by luxas** [comment]
Or, alternatively, use https://github.com/kcp-dev/kcp, which should be compatible with existing Kubernetes client CRD interfaces, and provides in-cluster authentication, etc. for free AFAICS

**Comment by Skarlso** [comment]
If I understand correctly, the standardisation is aimed at EVERY API. Not just Kubernetes related ones, right?

**Comment by bigkevmcd** [comment]
Yes, basically "no hand-rolled APIs" :-)
