### ISSUE TITLE
Fix the dev tag builder action

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/profiles#177]
The dev tag builder now builds on push, that's incorrect because that looks at the fork. We aren't pushing into weaveworks/profiles.

This should be on: pull_request.

**Comment by Skarlso** [comment]
I have no idea what to do. I'm parking this until I find a solution to create the dev tags on the profiles repository when there is a pull request without exposing a secret via Github Actions. :/

**Comment by cPu1** [comment]
Not relevant anymore
