### ISSUE TITLE
Remove `spec.name` field from ProfileDefinition

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#194]
AFAIK it is not used, and it is confusing to have it when `metadata.name` exists. We should have just the one.

**Comment by aclevername** [comment]
I think its the other way round, we don't use `metadata.name`, sorry if I was unclear.

**Comment by Callisto13** [comment]
you were very unclear! for shame!

**Comment by bigkevmcd** [comment]
Yes, drop it from the spec, the ObjectMeta.Name is where folks would expect us to get it from :-)
