### ISSUE TITLE
[Spike] How can we be smarter about values

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#197]
Right now users can only set values on individual Helm artifacts.

Users need to be able to:
- Configure single values to be applied to N chart artifacts
- Set values and other artifact types

These 2 needs may well be separate concerns, or they may influence each other. Please split as you like.

The outcome should be a proposal(s).

**Comment by Skarlso** [comment]
Okay, the proposal stands, let's re-visit this, once it becomes an actual issue.
