### ISSUE TITLE
Find a permanent way to nicely ignore kustomize yaml change

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/profiles#232]
We could do the following:

That file config/manager/kustomization.yaml is only changed when doing development and running local-dev. We could extract that Makefile action to call something else which, when done, reverts the change to the image resource with `kustomize edit remove resource`.

We could require anyone in the Development readme to run the following command:

```
git update-index --assume-unchanged config/manager/kustomization.yaml
```

This will effectively ignore changes to this file forever but is something that have to be done manually.

**Comment by aclevername** [comment]
duplicate? https://github.com/weaveworks/profiles/issues/179

**Comment by Skarlso** [comment]
Ops.............. thanks 🤦
