### ISSUE TITLE
Build up troubleshooting and FAQ sections of docs

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#236]
Might also be a good job for the person who did [this](https://github.com/weaveworks/profiles/issues/234), or anyone else who is less familiar with profiles.

**Comment by Skarlso** [comment]
Please put every documentation into https://github.com/weaveworks/profiles-userdocs/ from now on. userdocs in this repository will be removed soon.

**Comment by Himangini** [comment]
Closing this off since we no longer need this.
