### ISSUE TITLE
Improve how we do the docs sidebar

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#237]
Currently the sidebar order is determined in individual files. I.e. they all have the following:

```md
 ---
 sidebar_position: 6
 ---
```

which as you can imagine is a pain to update when we want to change ordering or add more pages in the middle.

Likewise there is a `_category_.json` file in each docs subfolder like this:
```json
 {
   "label": "Writing Profiles",
   "position": 3
 }
```

There is a way to do this in one place: https://docusaurus.io/docs/sidebar

**Comment by Skarlso** [comment]
Please put every documentation into https://github.com/weaveworks/profiles-userdocs/ from now on. userdocs in this repository will be removed soon.
