### ISSUE TITLE
Add a search bar to docs(?)

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#240]
Search bars in docs are the best thing since sliced bread, but adding them in Docusaurus might be a pain https://docusaurus.io/docs/search.

WeGo docs do not have a search bar, which is awful, but maybe they have a good reason.

**Comment by Himangini** [comment]
I am inclined to get the search added to our docs website, also shared this with Bianca and she too liked this idea. 
Let's aim to get this done when the remaining subtasks for this epic are done. 
Looking at the docusaurus docs to get the search API for free we need to tick this [checklist](https://docsearch.algolia.com/docs/who-can-apply/#the-checklist). Seems to me that we qualify for the free version, but might need some investigation.

**Comment by Skarlso** [comment]
Please put every documentation into https://github.com/weaveworks/profiles-userdocs/ from now on. userdocs in this repository will be removed soon.

**Comment by Himangini** [comment]
Closing this off since we no longer need this
