### ISSUE TITLE
Should we version our docs?

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#241]
Maybe a good idea, might be more trouble than it is worth.

You decide!

https://docusaurus.io/docs/versioning

**Comment by Himangini** [comment]
So apparently the versions on weave gitops docs are related to wego [versions ](https://docs.gitops.weave.works/docs/0.0.5/intro). We can explore the idea of documenting different versions of profiles/pctl but for now, seems like too much work 😅.  Let's revisit this when we get other subtasks done :)

**Comment by Skarlso** [comment]
Please put every documentation into https://github.com/weaveworks/profiles-userdocs/ from now on. userdocs in this repository will be removed soon.

**Comment by Himangini** [comment]
Closing this off since we no longer need this.
