### ISSUE TITLE
Setup slack bot for posting new releases in #profiles channel

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#249]
Would be nice if we automatically posted in the #profiles channel when a new `pctl` and `profiles` release are cut, along with the release notes. Similar to how we do in #aws-dev for eksctl

**Comment by Skarlso** [comment]
Created corp issue to track adding a slack_webhook secret to profiles.

**Comment by Skarlso** [comment]
As per security considerations, we are going to use a this slack actions: 
https://github.com/voxmedia/github-action-slack-notify-build

And create a Github Actions bot that can then post to the profiles channel, and use a Bot Token as a secret.

**Comment by Skarlso** [comment]
PCTL is yet to have a slack bot for releases.

Same approach as for Profiles. Needs a different bot, and the YAML.
