### ISSUE TITLE
Install by generating a ProfileSubscription

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#26]
**What feature/behavior/change do you want?**

Install a profile by generating a ProfileSubscription, that can install Profile with a secret or configmap. (assuming config map exists in cluster.)

```
$ pctl install weaveworks/nginx-ingress --namespace europe --config-secret=service-config-secret
apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
...
```

I can then apply that yaml to my cluster and see that my profile is installed with my values set.

**Why do you want this feature?**

I want to be able to create a subscription to a specific profile.

**Comment by Callisto13** [comment]
Questions about this feature:

1. We talk about "subscribing" to a profile, so what language do we want here: `pctl subscribe` or `pctl install`
2. Do we want subscription tied to catalogs (at this point in the implementation)? ie: if you ask to install a profile which is _not_ in your catalog, do we want to error?

**Comment by Callisto13** [comment]
blocked on https://github.com/weaveworks/profiles/issues/25

**Comment by Callisto13** [comment]
@bigkevmcd were you going to summarise the chat we had about this last week here?

**Comment by Callisto13** [comment]
For initial implementation we are going to only install (or in the case of this story generate a yaml for installation) a profile which is available in a catalog.

```
pctl --catalog-url 127.0.0.7:8000 install nginx
```

In the future we will add the following features:
1. Install profile _not_ in catalog from raw url
2. Allow orgs to "lock down" clusters so that users can _only_ install profiles which are listed in catalogs

but these can be left for now (i will create follow-u stories)

**Comment by bigkevmcd** [comment]
I think this should write out a profile.yaml, subscription, and whatever resources are generated by the profile installation (HelmRelease, GitRepository etc.).

**Comment by Callisto13** [comment]
Bumping up to M points as we need to think about how we do ownership of children

**Comment by Callisto13** [comment]
@bigkevmcd could you explain why we have decided to keep all generated artifacts in the instance repo? We have some concerns that it breaks a lot of the purpose of pctl/profiles

**Comment by bigkevmcd** [comment]
I'll dig further, but a Profile is nested Profiles.

**Comment by Callisto13** [comment]
From the discussion today we are no longer generating anything other than a profile subscription yaml when we install.

**Comment by Callisto13** [comment]
@Skarlso see comment above
