### ISSUE TITLE
Create a tutorials section in to documentation

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/profiles#263]
@Chanwit was so nice as to provide us with a lovely tutorial of him setting up the very first user profile.

He documented this here https://docs.google.com/document/d/1fGjVDloLYmJDGbzYAPsAKE62ukKzSvM1fXGIvql4k0g/edit

I think we should add this as a tutorial, or a blog post or something like that on our documentation for https://profiles.dev.

**Comment by Himangini** [comment]
there's a blog section in profiles.dev docs, currently not visible :)
