### ISSUE TITLE
I can install a profile by updating the gitops repository with the subscription

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#27]
**What feature/behavior/change do you want?**

As per story #26 but putting the profile subscription into a git repository.

**As a user:**
1. I have an existing gitops repo in Github. This repo is connected to Flux running in my cluster
1. I `cd` to a local directory which is my gitops repo
1. I run the `pctl` command to install a profile _with_ secret values provided via a config map
1. I see output telling me that
    1. A new branch has been created in my repo
    1. A single commit has been added to that branch
    1. A PR has been opened on my gitops repo from that new branch against my default branch
    1. A link to the PR which I can merge
1. I can navigate to that PR in my gitops repo
1. I can see that the PR adds a single ProfileSubscription yaml file, which details the profile I requested in my initial install command.
1. I can merge that PR, and I should see that:
    1. My profile is installed into my cluster by Flux
    1. The values I have requested have been applied

**Example UI:**
```sh
$ pctl install weaveworks/nginx-ingress --namespace europe --config-secret=service-config-secret
Branch 'install-nginx-agf10' created with Profile installation.
Pull Request opened on GitHub repository https://github.com/repo.
You can merge this PR by visiting:
https://github.com/repo/pull/N

# user merges PR
# waits for flux to pick up

$ kubectl get pods # etc
# wooo such profile
```

**Why do you want this feature?**

We're GitOps!

## Notes
Take a look at https://github.com/gitops-tools/pkg for creating a branch easily

**Comment by Callisto13** [comment]
@Skarlso UX and product outcomes updated above

**Comment by Skarlso** [comment]
Yes
