### ISSUE TITLE
Use `apiextensionsv1.JSON` type for Helm default values

### ISSUE THREAD

**Issue by hiddeco** [weaveworks/profiles#275]
I had a look at the Helm related side of profiles, and was wondering if there is a specific reason the `defaultValues` (shown here: https://profiles.dev/docs/tutorial-basics/create-a-profile/) is of a type string.

Our experience with the helm-controller, because it actually represents a YAML structure, is to use the [`*apiextensionsv1.JSON` structure from the Kubernetes core](https://github.com/fluxcd/helm-controller/blob/v0.11.2/api/v2beta1/helmrelease_types.go#L150-L152). The added value of this is that it ensures things are properly validated (or can be validated pre-commit using tools like `kubeval`).

While the result is still passed on to a `ConfigMap` key/value (which doesn't really care about what you put into it, really), this at least ensures any major formatting issues are caught before the helm-controller starts borking.

**Comment by aclevername** [comment]
> > Having the schema state its type *apiextensionsv1.JSON is actually quite confusing, given that yaml is supported. This is almost a non-starter to me as I imagine most people will expect to provide a yaml snippet for setting helm values.
> 
> That is the point, using this type ensures that if you pass YAML to this field, it is properly (un)marshaled in to/from JSON ensuring the data there is valid structured YAML/JSON. In addition, users would no longer have to do:
> 
> ```yaml
>         defaultValues: |
>           service:
>             type: ClusterIP
> ```
> 
> but can instead do:
> 
> ```yaml
>         defaultValues:
>           service:
>             type: ClusterIP
> ```
> 
> Also: anything in Kubernetes is JSON, YAML is just used in declarative configuration usually because it is easier to type :-)

That is terribly confusing :see_no_evil:

**Comment by stefanprodan** [comment]
@aclevername maybe an example is helpful: here is how flux CLI takes values.yaml files from disk and merges them into a `apiextensionsv1.JSON` https://github.com/fluxcd/flux2/blob/main/cmd/flux/create_helmrelease.go#L201-L228

**Comment by aclevername** [comment]
> Having the schema type `*apiextensionsv1.JSON` is what makes it a YAML, as now we ask users for a string that is supposed to be YAML.

I still think thats super unclear though. If I'm someone browsing the `profiles.dev` docs and I see that the type is `apiextensionsv1.JSON` I'm going to assume it means json and that yaml is not supported. I don't personally think its worth changing.

**Comment by stefanprodan** [comment]
>  If I'm someone browsing the profiles.dev docs and I see that the type is apiextensionsv1.JSON I'm going to assume it means json and that yaml is not supported

Then solve the issue in the docs, document that this field supports in-line YAML. We use this exact type in the [HelmRelease CRD](https://fluxcd.io/docs/components/helm/helmreleases/) and no user got confused so far.

**Comment by Callisto13** [comment]
I'm still not sure what we gain by this 🤔 . The difference between needing a `|` and not needing one is pretty negligible.

As Jake said, this file is never parsed by the API. At install time we simple copy the value of `defaultValues` into the corresponding [ConfigMap string value](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5976-L5997). Folks have been happily writing configmaps with this supposition for a while now, and it is easy for us to write in our docs "write it like you would a configmap". The whole "unmarshal then re marshal" dance just seems like extra code we don't need 🤷‍♀️ .

**Comment by Callisto13** [comment]
Also, this discussion is probably irrelevant, as the way we do values is going to change a lot soon 🙃
