### ISSUE TITLE
Prepare some slides for how profiles works (UX and internal)?

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#296]
I saw one of our CREs asking in Flux channel if there were any handy slides he could use to help deliver a workshop, and was wondering if this would be a good/useful thing for us to have ready to go for CREs/SAs/Marketing folks? Should probably wait until after we have done the rebrand.

What do people think?

**Comment by darrylweaver** [comment]
CX is working on a profile catalog and our internal slides for this work are here: 
https://docs.google.com/presentation/d/13goS5arsLa-ccxpepEuMtWhK-T_Z85Ojrl1qxHxdNqE/edit?usp=sharing

**Comment by Himangini** [comment]
Closing this since there are internal slides created by the CX team.
