### ISSUE TITLE
Write technical proposal for Profiles Integration into Weave GitOps

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#313]
Product doc: https://www.notion.so/weaveworks/Integrate-Profiles-into-Weave-GitOps-c73c2e04759a49ef93b3ba5023c6dc3e

Same drill as last time. Somebody writes, everybody interacts and the team owns as a whole. Fun times.

First step is to go through the product doc;
- ask any questions
- iron out any uncertainty
- **determine our scope**

**Outcome:**
- A googledoc
- Detailing (at a minimum)
  - The scope of this team's work (goals, non-goals)
  - A high level implementation plan
  - Some closer details of the above high level plan
  - Identify User scenarios mentioned in the Product Initiative doc which do not apply to PitchBlack team

_feel free to add more if I have missed anything_

**Comment by aclevername** [comment]
As discussed with @Himangini this is now just focusing on the CLI integration for now.

**Comment by Himangini** [comment]
Technical doc [here ](https://docs.google.com/document/d/1CRtwXCDvLR-VurbzmRWzBL4d8NQuTns_QiS44V2dD5g/edit#heading=h.lyxc8h644ba3)

**Comment by aclevername** [comment]
closing as the doc is complete

**Comment by Himangini** [comment]
Keeping it open till we finalize the implementation plan and add it in the doc
