### ISSUE TITLE
Set HelmRepository to poll for new helm-chart releases by default

### ISSUE THREAD

**Issue by foot** [weaveworks/profiles#327]
**What feature/behavior/change do you want?**

When specifying a helm-chart as the profile artefact, set the `interval` in the generated `HelmRepository` to a non-zero value so that it polls for new helm-chart releases. (Maybe `1m`?)

**Why do you want this feature?**

Its a slightly nicer UX. When a user manually changes the `HelmRelease.version` to a new version _that was not available when the profile was installed it_ will Just Work. Rather than the current state of an error hiding the `source-controller` logs that the version could not be found.

**Comment by aclevername** [comment]
@foot thanks for opening the issue! Do you think the author/installer would want to ever set a custom value for this? Or is just hard coding the value to be `1m` in enough :smile: ?

**Comment by foot** [comment]
Great question. We get by with `1m` and have not changed it. 
- AFAIUI this is not using up GITHUB_TOKEN requests. But maybe there are certain helm chart repos that _do_ rate limit? 🤔 
- If you're airgapped and want to stop an error from appearing in the logs you might want to stop this?

I think `1m` is a pretty good default. The user can modify it post-profile install too. Scripting a modification post-install might be a slight pain?

Its not our use case.. but I can see how someone will eventually want it.

**Comment by aclevername** [comment]
> Great question. We get by with `1m` and have not changed it.
> 
> * AFAIUI this is not using up GITHUB_TOKEN requests. But maybe there are certain helm chart repos that _do_ rate limit? thinking
> * If you're airgapped and want to stop an error from appearing in the logs you might want to stop this?
> 
> I think `1m` is a pretty good default. The user can modify it post-profile install too. Scripting a modification post-install might be a slight pain?
> 
> Its not our use case.. but I can see how someone will eventually want it.

Thanks! Lets just hardcode `1m` for now and expose it down the line if we get the need :smile: 

Is this high priority, or can it wait until it gets discussed in our team planning next Wednesday @foot ?

**Comment by foot** [comment]
> Is this high priority

No rush from here 👍

**Comment by Himangini** [comment]
maybe 5-10 mins :D

**Comment by aclevername** [comment]
shipped in pctl `0.10.0`
