### ISSUE TITLE
Allow profiles to have a way of expressing conflicts

### ISSUE THREAD

**Issue by darrylweaver** [weaveworks/profiles#328]
Profiles are a gitops package management system.
In order to provide the full functionality of a package management system there should be a way of expressing profiles that would conflict with each other.

For example, if there was a Prometheus profile, which was then combined with an ELK stack profile, to create an Observability Profile, then that would itself conflict with the Prometheus profile and ELK stack profile as both should not be installed together.

There could also be another profile that combines Prometheus with Loki for a different Observability profile, e.g Observability-alternative.  Again, the Observability profiles should not be installed together.

For a single catalog of profiles there should at least be consistency that you cannot attempt to install Profiles that would conflict using the same namespaces or CRDs or resource names that would mean they cannot be installed at the same time.

Another example would be 2 profiles that install the same software but have configuration differences.
For example,  you could have a profile for Prometheus that is configured to send outgoing alerts to an external alert system such as Pagerduty and another profile which sends outgoing alerts to OpsGenie.  They use the same parameters otherwise and so would conflict with namespaces and other resource names and should not be installed together.

Suggestion would be to include in the ProfileDefinition resource a new field: 
Conflicts: <comma seperated list of conflicts by name>

This would allow a catalog maintainer to list profiles in the same catalog that conflict and cannot be installed together.

**Comment by aclevername** [comment]
Thanks for opening the issue @darrylweaver! 

> In order to provide the full functionality of a package management system there should be a way of expressing profiles that would conflict with each other.

does functionality like this in `helm` already exist? Wondering how this problem has been solved by other tools.

> Suggestion would be to include in the ProfileDefinition resource a new field:
Conflicts:
This would allow a catalog maintainer to list profiles in the same catalog that conflict and cannot be installed together.

That seems like quite a reasonable approach but I do wonder how well this scales when catalog get rather large. Would having the ability to dry-run an installation, and get warnings if the installation would interact with existing kubernetes resource be more insightful?

**Comment by darrylweaver** [comment]
Helm has no mechanism for detailing conflicts.  The main changes in helm focus on scoping resources to the namespace the helm release is installing into.  However, helm charts can include cluster scoped resources which can conflict with other cluster scoped resources.  So the problem exists in helm too.  You can install one helm chart (which includes CRDs) and then try and install another (which installs the same CRDs) and you will get an error about conflicting resources.
The concept of moving to the left and giving an error as soon as possible, rather than relying on later errors would dictate that we should error before attempting to install a conflicting chart.
This would not be a concern for namespace scoped helm charts, unless of course the namespace name is identical in which case the same problem occurs with conflicting resources.
A dry run with errors that need to be interpreted is something I would expect to catch an error where there is a missing conflict label and so would be useful.
If we know what conflicts exist, we should add that to a catalog we are developing to allow the WGE UI to query that info to present to the user so they do not even attempt a set of conflicting profiles. 
A dry run should be the next step to catch missing conflicts and only if this passes, then do the actual install.

**Comment by bigkevmcd** [comment]
@darrylweaver Interesting idea, thank you for this!

I think we can error early, at the point where the `pctl` is installing the profile into the repository, and yes, we could have conflicts, my first thought was the richness of https://www.debian.org/doc/debian-policy/ch-relationships.html but that might be more than we need...

So, yes, I think we could add something like...

```yaml
apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: test-profile
spec:
  conflicts:
    - name: my-other-profile
       catalog: weaveworks # <- this is tricky, because of airgapping and catalog naming
       version: v1.0.1
```
The UX could look something like (assuming a repository with `test-profile` already installed

```shell
$ pctl add weaveworks/my-other-profile
Error: The profile weaveworks/my-other-profile conflicts with weaveworks/test-profile and is unable to be installed
```

We could also provide an additional command something like:

```shell
$ pctl verify-installs --directory /tmp/profiles
```
This would need to run with access to the cluster with the catalog, but would could avoid race issues around installing profiles in PRs where conflicting installs have yet to land.

**Comment by josefaworks** [comment]
+1 for error messages :)

**Comment by Skarlso** [comment]
As a note, if a conflicting profiles has nested profiles in it we also implicitly will mark them as conflicting as well?

**Comment by bigkevmcd** [comment]
@Skarlso Interesting question, I'd say no, as you might be able to install some subcomponent in a way that doesn't conflict?

**Comment by Skarlso** [comment]
That increases the complexity of the setting then, right? Like, ignore that profile but don't ignore the nested things in it. Or ignore the nested things but don't ignore some of them... I mean we can, of course, do something like loop over all nested profiles and ignore them if a conflict exists for it, but it would duplicate the conflict settings. Something like, ignore these nested profiles, but also generally ignore this profile in this section but don't ignore any nested profiles.... etc. :)

**Comment by bigkevmcd** [comment]
I don't think it does, if you say "X conflicts with Y" that's basically saying you can't install X and Y at the same time, so, install of Y should fail if X is already installed, and no more than that.

That doesn't mean you'd get a partial installation of Y if the subcomponents of Y weren't blocked.

**Comment by Skarlso** [comment]
Ok, but what about the artifacts of profiles X? Is profiles X the conflicting one or some of its artifacts are? Because we basically flatten all of nested profiles' artifacts into profile X. I guess, before flatten we can go over some of the conflict lists. 🤔

**Comment by bigkevmcd** [comment]
I'm not sure it matters, if profile Y is declared to conflict with profile Y, that means they can't be installed into a repo concurrently.

**Comment by darrylweaver** [comment]
> my first thought was the richness of https://www.debian.org/doc/debian-policy/ch-relationships.html but that might be more than we need...

That was also my first thought when I read that profiles are a package management system.  If it is, then although we don't need it now, we are eventually going to need pretty much all of that.
If we can describe profiles as not a full package management system, but a curated set of instructions guaranteed to work together in this one configuration, i.e. 'golden profiles' which are our tool to create deployments for our customers that are managed in WGE-UI then we don't need the full relationships model.

With regards to conflicts and nesting, here is an example:

I have a catalog repository, I have the following profiles :
kube-prom-stack/
cert-manager/
use-cases-base/
             cert-manager
             kube-prom-stack
use-case1/
             use-cases-base
             more-artifacts-1
 use-case2/
             use-cases-base
             more-artifacts-2

I need to flag use-case1 and use-case2 as conflicting with each other.

But I would also need to make sure if either use-case1 or use-case2 are installed then I must not also install any of the nested profiles, cert-manager, kube-prom-stack, or use-cases-base.
However, these conflicts can be calculated as they are nested profiles and so could automatically be marked as conflicting.

**Comment by bigkevmcd** [comment]
> However, these conflicts can be calculated as they are nested profiles and so could automatically be marked as conflicting.

This feels like an odd case?

Let's say I have an "observability profile with Cortex" with grafana, prometheus and cortex and another "observability profile with InfluxDB" it feels like those should conflict, but only because it doesn't make sense to install them at the same time.

But, to say that the "grafana" and "prometheus" parts conflict doesn't seem correct?
