### ISSUE TITLE
I can install a profile with more than one artifact

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#45]
Currently in `pkg/profile/artifact.go` we simply get the first index of the artifacts array.

**Comment by aclevername** [comment]
the `nginx-profile` has ` yaml` branch with a yaml artifact. Once this story is complete lets merge that into main and have the profile have two artifacts, one a helm chart and one a raw yaml

**Comment by aclevername** [comment]
@Callisto13 @bigkevmcd how do we want to handle helm values now that the profile can contain multiple helmchart artifacts? Currently its 1 top-level set of values passed into both helmcharts, which obviously causes some limitations. Do we want to start scoping the variables per-artifacts?

**Comment by Callisto13** [comment]
Good question. The solution really depends on how much the user knows about underlying artifacts and the values they expose. I recall in one design, we had the profile author define a set of variables which could be set at the top level, which were then applied to the correct artifact so the user didn't need to know about what went where (the `profile_values.yaml` file or smthing).

I think let's have a ticket to do this and we can discuss.
