### ISSUE TITLE
Install a profile from a private repository

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/profiles#49]
# Motive
Currently the profile fetching in the Git implementation is not using authentication. We would like to provide private repository options as well, which means authentication needs to be implemented there.

## Discussion 

What kind of authentication that will be is up for debate and needs to be further discussed.

### Proposition 1

A client factory.
TODO: flesh this out

### Proposition 2
TODO: flesh this out

A chain pattern of providers.

**Comment by bigkevmcd** [comment]
I see these as orthogonal concerns.

Ultimately, we need to be able to read files from Git repositories.

So, for a given "repository URL", we need to create something that we can use to read the files from that repository.

The contract, is "I give you a repo URL, you give me something that will work to read files from the repo" ?

How the contract is fulfilled, internally, is not really the concern of the caller?

It could have a map of hostnames -> clients, it could have a mapping of repoURLs -> client parameters (API endpoint, authentication mechanism), it could go through all the possible authentication mechanisms, and ask them to try accessing the repo, and the first to return "yes" is the "chosen one".

But, that's for the implementation of the thing that is contractually obligated to return a client that can read files from the repo to know about?

What this means, is that a factory could use a "chain of responsibility" as an implementation detail?

**Comment by Skarlso** [comment]
That makes sense, yes.

**Comment by aclevername** [comment]
https://github.com/weaveworks/pctl/issues/103
https://github.com/weaveworks/pctl/issues/104
