### ISSUE TITLE
I can delete a catalog source from my cluster

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#51]
The API needs to handle removing things from the profiles array which are associated with that catalog.

This would be useful to have sooner rather than later, because right now the integration tests keep failing when run multiple times as the in memory list persists between runs

**Comment by cPu1** [comment]
>I can delete a catalog from my cluster

>The API needs to handle removing things from the profiles array which are associated with that catalog.

Is this issue about removing a profile from a catalog, or a catalog itself?

**Comment by Callisto13** [comment]
a catalog itself. there is another story to handle updating a catalog (adding/removing profiles from an existing catalog)
