### ISSUE TITLE
I can set config values for multiple Helm charts

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#64]
From https://github.com/weaveworks/profiles/issues/45#issuecomment-817805531

> how do we want to handle helm values now that the profile can contain multiple helmchart artifacts? Currently its 1 top-level set of values passed into both helmcharts, which obviously causes some limitations. Do we want to start scoping the variables per-artifacts?

**Comment by aclevername** [comment]
As our approach to values changes I think this issue is out of date. Closing
