### ISSUE TITLE
Handle multiple ProfileCatalogSources with the same name in different namespaces

### ISSUE THREAD

**Issue by cPu1** [weaveworks/profiles#66]
The `pctl show` commands shows details of a profile:
```
pctl --catalog-url http://localhost:8000 show <catalog-name>/<profile-name>
```
The catalog name here comes from `metadata.Name` of the `ProfileCatalogSource` resource, but one can add multiple `ProfileCatalogSource` resources with the same name to different namespaces. It's not clear what the `show` command should return in this case.

**Comment by bigkevmcd** [comment]
How about we use the `types.NamespacedName` as the name?

We could even be nice, and accept the name, if it's unambiguous?

**Comment by cPu1** [comment]
>How about we use the types.NamespacedName as the name?

As the catalog's name? That'd look like `namespace/catalog`, e.g., `default/weaveworks-catalog`. What would a user specify in `pctl show`, the namespaced name? That'd result in the following command:

```
pctl --catalog-url http://localhost:8000 show default/weaveworks-catalog/<profile-name>
```

**Comment by bigkevmcd** [comment]
> > How about we use the types.NamespacedName as the name?
> 
> As the catalog's name? That'd look like `namespace/catalog`, e.g., `default/weaveworks-catalog`. Would a user specify the namespaced name in `pctl show`? That'd result in the following command:
> 
> ```
> pctl --catalog-url http://localhost:8000 show default/weaveworks-catalog/<profile-name>
> ```

> We could even be nice, and accept the name, if it's unambiguous?

**Comment by bigkevmcd** [comment]
Alternatively, we could return an error if it's ambiguous with the namespaces that the name is available in?

But, if it's unambiguous, we return the named profile
