### ISSUE TITLE
[Investigate] How can we discover outdated profiles?

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#71]
**Example UX:**
```
$ pctl outdated --namespaces dev-pesto,dev-pitch-black
dev-pesto       weaveworks/nginx-ingress 1.10.2 [upgradable from: 1.10.1] auto (6hrs)
dev-pitch-black weaveworks/nginx-ingress 1.10.2 [upgradable from: 1.10.1] manual
```

**Outcomes for this ticket:**
The aim here is to investigate/play around/spike and come up with a good solution (or several potential solutions) for how we discover when profiles fall out of date.

Add any ideas with pros and cons in this thread (or link to a googledoc if the discussion and investigation could get lengthy).

This ticket is complete when a follow up user feature has been created to actually implement the work.

**Comment by aclevername** [comment]
#101
