### ISSUE TITLE
Filter returned results based on access to catalog sources

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#72]
**What feature/behavior/change do you want?**

Currently we cache the results, but we should only return results from ProfileCatalogSources that the "current user" has access to.

This probably involves querying for accessible sources, and then filtering the results based on the accessible elements, we don't need to reindex.

**Why do you want this feature?**

Enterprise access-control is used to control access to objects (via policies etc), and we should make it easy to prevent installation of profiles that user doesn't have access to.

**Comment by aclevername** [comment]
@bigkevmcd worth prioritising?

**Comment by bigkevmcd** [comment]
@aclevername I suspect we want to wait 'til we've got authn/authz in front of this :-)

The "how" is also a little bit fuzzy (there's a strong option, but nailing it down isn't yet complete).
