### ISSUE TITLE
I can update my profile subscription values

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#74]
**What feature/behavior/change do you want?**
After deploying my profile subscription with a set of values I want to be able to update the values and have the changes propagate to the running deployments

After https://github.com/weaveworks/profiles/issues/69 this might be a no-op for certain cases as changes to the subscription will result to changes in the artifacts. Regardless testing needs to be added + how this works when using a configmap instead of a list of values

**Why do you want this feature?**
So that I can update my deployments

**Comment by Skarlso** [comment]
Things to document:

- [ ] Inline value modification works
- [ ] ConfigMap modification is not yet supported from helm-controller ( https://github.com/fluxcd/helm-controller/issues/42 )
- [ ] Potentially we could use https://github.com/bitnami-labs/kubewatch to create a webhook watcher. HelmRelease allows to create webhooks https://fluxcd.io/docs/guides/webhook-receivers/. We still feel though that this shouldn't be fixed on our end, but if flux decides to not do anything with it, we might still do something on our side then.
