### ISSUE TITLE
Improve pod names

### ISSUE THREAD

**Issue by bia** [weaveworks/profiles#77]
Currently,

> To check your subscription was successful, you can inspect the nginx pod: `kubectl describe pod [-n <namespace>] <pod-name>`. The pod name will be comprised of `profileSubscriptionName-profileDefinitionName-artifactName-xxxx`

The separation character `-` is always the same, whether the sections have semantic meaning, or not.

Is there some advantage (besides convention) to separating `artifactName` and `xxxx`?
I feel like `profileSubscriptionName-profileDefinitionName-artifactNamexxxx` without the last `-` is already an improvement because it's 3 items (instead of 4) for a human to parse.

~Could we use other UTF-8 characters here like
`profileSubscriptionName::profileDefinitionName-artifactNamexxxx`
or
`profileSubscriptionName<>profileDefinitionName-artifactNamexxxx`~

What do other people think?

**Comment by bigkevmcd** [comment]
There are issues around naming objects...limited to 63 characters, _and_ very limited in the valid characters.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

**Comment by bia** [comment]
Aha, so only `-` and lowercase alphanumerics are allowed.
In that case maybe

`profileSubscriptionName-profileDefinitionName---artifactNamexxxx`
as a format?

**Comment by bigkevmcd** [comment]
@bia that would work, we do need to work out what to do when it's > 63 characters too.

Do we trim from the front/back/something else?

**Comment by bia** [comment]
@bigkevmcd how important is `artifactNamexxxx` to be able to retrieve different types of data about the pod?

**Comment by bigkevmcd** [comment]
@bia I don't think it's particularly important, the objects are owned by the parent, and we can always find them, so we could just `generateName:` on them.

**Comment by bia** [comment]
Ok, so then let's trim the back (`artifactNamexxxx`)  if > 63 characters :)

and otherwise `profileSubscriptionName-profileDefinitionName---artifactNamexxxx` as a format?
