### ISSUE TITLE
Associating profile subscriptions with catalog entry

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#87]
**What feature/behavior/change do you want?**
I want to be able to associate what catalog, profile & version a subscription is linked to.

Currently a `ProfileSubscription` spec looks like:
```
spec
  profileURL: https://github.com/weaveworks/nginx-profile
  branch: main
```

Using [pctl](https://github.com/weaveworks/pctl) you can install a profile from a catalog entry, e.g. :
```
pctl install nginx-catalog/weaveworks-nginx # generates profile_subscription.yaml

cat profile_subscription
...
spec:
  branch: main
  profileURL: https://github.com/weaveworks/nginx-profile
```

This doesn't leave any connection to what catalog entry was used to generate the profile. I want to be able to get the catalog name and version from the subscription.

## Proposal
You can keep the current way of specifying a profile subscription directly:
```
spec
  profileURL: https://github.com/weaveworks/nginx-profile
  branch: main
```

Or alternatively you can just provide the catalog name, version and profile name:
```
spec
  profileName: nginx
  catalog: weaveworks-catalog
  version: 1.0
```
Which would get mutated by a mutating webhook to fill in the `profileURL` and `branch` by looking up the catalog entry, e.g.:
```
spec
  profileName: nginx
  catalog: weaveworks-catalog
  version: 1.0
  profileURL: https://github.com/weaveworks/nginx-profile
  branch: main
```

This might be a good opportunity to think about renaming the spec fields, and possibly grouping them to something like:
```
spec
  name: nginx
  catalog: weaveworks-catalog
  version: 1.0
  src: # something better than this
    url: https://github.com/weaveworks/nginx-profile
    branch: main # maybe "ref"?
```

**Why do you want this feature?**
so that I can clearly see what catalog & profile my profile subscription was generated from.

**Comment by aclevername** [comment]
@bigkevmcd thoughts?

**Comment by bigkevmcd** [comment]
I like this....

```
spec
  profileName: nginx
  catalog: weaveworks-catalog
  version: 1.0
  profileURL: https://github.com/weaveworks/nginx-profile
  branch: main
```

I suspect that we want to only reconcile the profileURL _at reconciliation time_ via the catalog.

**Comment by aclevername** [comment]
> I like this....
> 
> ```
> spec
>   profileName: nginx
>   catalog: weaveworks-catalog
>   version: 1.0
>   profileURL: https://github.com/weaveworks/nginx-profile
>   branch: main
> ```
> 
> I suspect that we want to only reconcile the profileURL _at reconciliation time_ via the catalog.

sounds good, presumably branch as well as the two are tightly coupled

**Comment by bigkevmcd** [comment]
> sounds good, presumably branch as well as the two are tightly coupled

Or the version?

**Comment by bigkevmcd** [comment]
i.e. I think you can install from a repo/branch, or a catalog entry/version ?

**Comment by aclevername** [comment]
> i.e. I think you can install from a repo/branch, or a catalog entry/version ?

yes thats essentially the desired out come, but in the later case I think we should still write down the repo/branch in the spec, as its useful to see "this is actually what I'm installing from", given the catalogs can change underneath you

**Comment by bigkevmcd** [comment]
Catalogs should really only be changing underneath you via GitOps?

Which would be intentional?

**Comment by aclevername** [comment]
if we update the spec as part of the reconciliation, does this cause flux to detect a drift as the subscription yaml has changed in cluster vs local git file?

**Comment by Callisto13** [comment]
see also https://github.com/weaveworks/profiles/issues/89
